### ISSUE TITLE
Icon theming issue

### ISSUE THREAD

**Issue by spookykidmm** [michelelacorte/FlickLauncher#53]
On Flick Launcher, I have Amphetamine Icon pack, and since its newer, very few icons are themed. This would be fine, but icons that are not themed have an odd white circle around them, even though I didn't apply an icon mask. I know it's a bug because newly installed apps without an icon theme are actually fine and don't have the circle
Specs:
Samsung Galaxy S7 Edge AT&T
Android 7.0
Latest Play Store Version of Flick Launcher

![](http://i.imgur.com/mkm2Rdt.png)

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by michelelacorte** [comment]
Hi,
Thanks for the report, I will suggest you to check latest apk in the telegram group, I've fixed more things, https://t.me/FlickLauncherTester

**Comment by spookykidmm** [comment]
Thank you, but the problem persists

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
